[project]
name = 'Decentralized-Specialized-Handmade-Jewelry-Verification'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.artisan-verification]
path = 'contracts/artisan-verification.clar'
clarity_version = 2
epoch = 2.5

[contracts.design-registration]
path = 'contracts/design-registration.clar'
clarity_version = 2
epoch = 2.5

[contracts.material-certification]
path = 'contracts/material-certification.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
